---
title: "Project Forecasting"
author: "Henry Minör"
date: "9 2 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
rm(list=ls())

library(tseries)
library(moments)
library(dplyr)
library(sandwich) ## used to compute NW SE's
library(lmtest)
library(tidyverse)

# function to retrieve path for source file
getCurrentFileLocation <-  function() {
  this_file <- commandArgs() %>% 
    tibble::enframe(name = NULL) %>%
    tidyr::separate(col=value, into=c(" key", "value"), sep="=", fill='right') %>%
    dplyr::filter(key == "--file") %>%
    dplyr::pull(value)
  if (length(this_file)==0) {
    this_file <- rstudioapi::getSourceEditorContext()$path
  }
  return(dirname(this_file))
}
# set working directory to current file location
file_dir <- getCurrentFileLocation()
setwd(file_dir)

# get utilities
source("../lib/utilities.R")
```




Transform the data
```{r}
chgch <- diff( log( CHIEPUINDXM ) )*100
chgus <- diff(log(USEPUINDXD))*100
logus<- log(USEPUINDXD)
logch<- log(CHIEPUINDXM)

```
Notice that the chinese data is non-stationary!! US data is stationary


Plot the data:
```{r}

pdf(file='graphs.pdf',width=7,height=5) ### all comments afterwards will split be add to the pdf file (until dev.off)


## raw data
par(mfrow=c(3,2))
myplot(datesus, USEPUINDXD, col="red2", main="USEPUINDXD")
abline(h=mean(USEPUINDXD) , lwd=2)

myplot(datesch, CHIEPUINDXM, col="red2", main= "CHIEPUINDXM")
abline(h=mean(USEPUINDXD) , lwd=2)

myplot(datesus, log(USEPUINDXD), col="red2", main="log USEPUINDXD")
abline(h=mean(log(USEPUINDXD)) , lwd=2)

myplot(datesch, log(CHIEPUINDXM), col="red2", main= "log CHIEPUINDXM")
abline(h=mean(log(USEPUINDXD)) , lwd=2)

myplot(datesus[2:length(datesus)], chgus, col="red2", main="Change US")
abline(h=mean(chgus) , lwd=2)

myplot(datesch[2:length(datesch)], chgch, col="red2", main= "Change China")
abline(h=mean(chgch) , lwd=2)


### QQ Norms
par(mfrow=c(3,2))
qqnorm(USEPUINDXD,col='tomato',main='US')
qqline(USEPUINDXD,lwd=2,lty=3)

qqnorm(CHIEPUINDXM,col='tomato',main='China')
qqline(CHIEPUINDXM,lwd=2,lty=3)

qqnorm(log(USEPUINDXD),col='tomato',main='log US')
qqline(log(USEPUINDXD),lwd=2,lty=3)

qqnorm(log(CHIEPUINDXM),col='tomato',main='log China')
qqline(log(CHIEPUINDXM),lwd=2,lty=3)

qqnorm(chgus, col="tomato", main='Change US')
qqline(chgus,lwd=2,lty=3)

qqnorm(chgch,col='tomato',main='Change China')
qqline(chgch,lwd=2,lty=3)

### histograms
par(mfrow=c(3,2))
hist(USEPUINDXD,50,freq=FALSE,col='tomato',border='darkred')

hist(CHIEPUINDXM,50,freq=FALSE,col='tomato',border='darkred')

hist(logus,50,freq=FALSE,col='tomato',border='darkred')

hist(logch,50,freq=FALSE,col='tomato',border='darkred')

hist(chgus,50,freq=FALSE,col='tomato',border='darkred')

hist(chgch,50,freq=FALSE,col='tomato',border='darkred')

### Kernels
par(mfrow=c(3,2))
plot( density(USEPUINDXD) ,paste("Kernel density of USEPUINDXD"), yaxs='i' )
polygon( density(USEPUINDXD), col="tomato", border='darkred' )

plot( density(CHIEPUINDXM) , paste("Kernel density of CHIEPUINDXM"),yaxs='i' )
polygon( density(CHIEPUINDXM) , col="tomato" , border='darkred' )

plot( density(logus), paste("Kernel density of logus"), yaxs='i' )
polygon( density(logus) , col="tomato" , border='darkred' )

plot( density(logch) ,  paste("Kernel density of logch"),yaxs='i' )
polygon( density(logch) , col="tomato" , border='darkred' )

plot( density(chgus) , paste("Kernel density of chgus"),yaxs='i' )
polygon( density(chgus),col="tomato" , border='darkred' )

plot( density(chgch) ,paste("Kernel density of chgch"), yaxs='i' )
polygon( density(chgch) , col="tomato" , border='darkred' )


dev.off()

```

Moments:
```{r}


mean(USEPUINDXD)
sd(USEPUINDXD)
skewness(USEPUINDXD)
kurtosis(USEPUINDXD)

mean(logus)
sd(logus)
skewness(logus)
kurtosis(logus)

mean(chgus)
sd(chgus)
skewness(chgus)
kurtosis(chgus)

mean(CHIEPUINDXM)
sd(CHIEPUINDXM)
skewness(CHIEPUINDXM)
kurtosis(CHIEPUINDXM)

mean(logch)
sd(logch)
skewness(logch)
kurtosis(logch)

mean(chgch)
sd(chgch)
skewness(chgch)
kurtosis(chgch)



```


Carry out tests for stationarity
```{r}
list <- list(USEPUINDXD ,CHIEPUINDXM, chgus, chgch, logus, logch)
list

for(i in list){
  adf.test(i)
}

## raw data
adf.test(CHIEPUINDXM)
adf.test(USEPUINDXD)
## log changes
adf.test((chgch))
adf.test((chgus))
## logs
adf.test(log(CHIEPUINDXM))
adf.test(log(USEPUINDXD))

```

Jarque-Bera test for normality:
```{r}

## raw data
jarque.test(USEPUINDXD)
jarque.test(CHIEPUINDXM)
## log changes
jarque.test((chgus))
jarque.test((chgch))
## logs
jarque.test(log(USEPUINDXD))
jarque.test(log(CHIEPUINDXM))
```


Autocorrelations:
```{r}
pdf(file='correlations.pdf',width=7,height=5) ### all comments afterwards will split be add to the pdf file (until dev.off)

par(mfrow=c(3,2), mar=c(3,3,3,3))
acf(USEPUINDXD, type = c("correlation"), col='darkorange2')
acf(CHIEPUINDXM, type = c("correlation"),  col='darkorange2')
acf(logus, type = c("correlation"), col='darkorange2')
acf(logch, type = c("correlation"), col='darkorange2')
acf(chgus, type = c("correlation"), col='darkorange2')
acf(chgch, type = c("correlation"), col='darkorange2')

dev.off()
```

Ljung-Box Tests:
```{r}
Box.test(USEPUINDXD , type = c("Ljung-Box"))
Box.test(logus , type = c("Ljung-Box"))
Box.test(chgus , type = c("Ljung-Box"))
Box.test(CHIEPUINDXM , type = c("Ljung-Box"))
Box.test(logch , type = c("Ljung-Box"))
Box.test(chgch , type = c("Ljung-Box"))

```


