---
title: "IS_Inv_Regression"
author: "Henry Minör"
date: "20 2 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
rm(list=ls())

library(tseries)
library(moments)
library(dplyr)
library(forecast)
library(sandwich) ## used to compute NW SE's
library(lmtest)
library(tidyverse)

getCurrentFileLocation <-  function() {
  this_file <- commandArgs() %>% 
    tibble::enframe(name = NULL) %>%
    tidyr::separate(col=value, into=c("key", "value"), sep="=", fill='right') %>%
    dplyr::filter(key == "--file") %>%
    dplyr::pull(value)
  if (length(this_file)==0) {
    this_file <- rstudioapi::getSourceEditorContext()$path
  }
  return(dirname(this_file))
}

file_dir <- getCurrentFileLocation()
setwd(file_dir)

# get utilities
source("./lib/utilities.R")

```

Read the data
```{r}
us <- read.csv("./data/uncertainty_full.csv")
datesus <- as.Date(DATE)

is <- us[1:(nrow(us)*0.8), ]

attach(is)
os <- us[(nrow(is)+1):419, ]

```

# Build the Models

##Industrial Prodcution
```{r}
## Use uncertainty index as single predictor for the variables

arma13 <- auto.arima(INDPRO_growth)
summary(arma13)
arma13_res <- arma13$residuals
arma13_hat <- INDPRO_growth+ arma13_res 
jarque.test(as.numeric(arma13_res))

acf(arma13_res)
pacf(arma13_res)

arma13_aic    <- (-2*arma13$loglik+2*6)/length(is)
arma13_bic    <- (-2*arma13$loglik+log(length(is))*6)/length(is) 

print(rbind(c('AIC', 'BIC'), c(arma13_aic, arma13_bic)))
par( mar=c(2,2,1,1) , mfrow=c(2,1) )
acf( arma13_res , ylim=c(-0.2,1) , lwd=5 , xlim=c(0,25) , col='darkorange2' , tck=0.02)
legend('topright',c('ACF'),col=c('darkorange2'),lwd=3)
pacf( arma13_res , ylim=c(-0.2,1) , lwd=5 , xlim=c(0,25) , col='darkorange2' , tck=0.02)
legend('topright',c('PACF'),col=c('darkorange2'),lwd=3)


### INDPRO-INDPRO
regINDPROINDPRO1 <- lm(INDPRO_growth ~ lag(INDPRO_growth))
summary(regINDPROINDPRO1)
nw.regINDPROINDPRO1 <- NeweyWest(regINDPROINDPRO1)
  coeftest(nw.regINDPROINDPRO1)

  
### INDPRO-EPU
regINDPROEPU1 <- lm(INDPRO_growth ~ lag(uncertainty_growth))
summary(regINDPROEPU1)

regINDPROEPU12 <- lm(INDPRO_growth ~ lag(uncertainty_growth) + lag(uncertainty_growth, n = 2))
summary(regINDPROEPU12)


regINDPROEPU123 <- lm(INDPRO_growth ~ lag(uncertainty_growth) + lag(uncertainty_growth, n = 2) + lag(uncertainty_growth, n =3) )
summary(regINDPROEPU123)



### INDPROCPI
regINDPROCPI1 <- lm(INDPRO_growth ~ lag(cpi_diff))
summary(regINDPROCPI)


regINDPROINDPROUNRATECPIEPU <- lm(INDPRO_growth ~ lag(INDPRO_growth) + lag(cpi_diff)  + lag(UNRATE) +lag(uncertainty_growth) +  lag(uncertainty_growth, n = 2))
summary(regINDPROINDPROUNRATECPIEPU)


regINDPROINDPROCPIEPU <- lm(INDPRO_growth ~ lag(INDPRO_growth) + lag(cpi_diff) + lag(UNRATE) +lag(uncertainty_growth) +  lag(uncertainty_growth, n = 2))
summary(regINDPROINDPROCPIEPU)

regINDPROINDPRO2UNEMP2CPI2EPU2 <- lm(INDPRO_growth ~ lag(INDPRO_growth) +lag(INDPRO_growth, n=2)  + lag(cpi_diff) + lag(cpi_diff, n=2) + lag(UNRATE) + lag(UNRATE, n=2) +lag(uncertainty_growth) +  lag(uncertainty_growth, n = 2))
summary(regINDPROINDPRO2UNEMP2CPI2EPU2)
coeftest(regINDPROINDPRO2UNEMP2CPI2EPU2)

NeweyWest(regINDPROINDPRO2UNEMP2CPI2EPU2)
#coeftest(NeweyWest((regINDPROINDPRO2UNEMP2CPI2EPU2)))


```


## Consumer Price Index
```{r}
### CPI
regCPI1 <- lm(cpi_diff ~ lag(cpi_diff))
summary(regCPI1)

regCPIEPU1 <- lm(cpi_diff ~ lag(uncertainty_growth))
summary(regCPIEPU1)

```


## Unemployment
```{r}
regUNEMPUNEMP1 <- lm(UNRATE ~ lag(UNRATE))
summary(regUNEMPUNEMP1)

regUNRATEEPU1 <- lm(UNRATE ~ lag(uncertainty_growth))
summary(regUNRATEEPU1)

regUNRATEEUP12 <- lm(UNRATE ~ lag(uncertainty_growth) + lag(uncertainty_growth, n=2))
summary(regUNRATEEUP12)


```
