---
title: "Project Forecasting"
author: "Henry Minör"
date: "9 2 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list=ls())

library(tseries)
library(moments)
library(dplyr)
library(sandwich) ## used to compute NW SE's
library(lmtest)
library(tidyverse)

getCurrentFileLocation <-  function() {
  this_file <- commandArgs() %>% 
    tibble::enframe(name = NULL) %>%
    tidyr::separate(col=value, into=c("key", "value"), sep="=", fill='right') %>%
    dplyr::filter(key == "--file") %>%
    dplyr::pull(value)
  if (length(this_file)==0) {
    this_file <- rstudioapi::getSourceEditorContext()$path
  }
  return(dirname(this_file))
}

file_dir <- getCurrentFileLocation()
setwd(file_dir)

# get utilities
source("../lib/utilities.R")
```

Read the data
```{r}
us <- read.csv("../data/daily/USEPUINDXD.csv")

attach(us)
datesus <- as.Date(DATE)

```

Transform the data
```{r}
logus<- log(USEPUINDXD)
chgus <- diff(log(USEPUINDXD))*100

```
Notice that the chinese data is non-stationary!! US data is stationary


Plot the data:
```{r}

pdf(file='../images/graphs.pdf',width=7,height=5) ### all comments afterwards will split be add to the pdf file (until dev.off)
## raw data
myplot(datesus, USEPUINDXD, col="red2", main = '')
abline(h=mean(USEPUINDXD) , lwd=2)

#myplot(datesus, log(USEPUINDXD), col="red2")
#abline(h=mean(log(USEPUINDXD)) , lwd=2)

myplot(datesus[2:length(datesus)], chgus, col="red2", main='')
abline(h=mean(chgus) , lwd=2)


### QQ Norms
qqnorm(USEPUINDXD,col='tomato', main='')
qqline(USEPUINDXD,lwd=2,lty=3)

#qqnorm(log(USEPUINDXD),col='tomato')
#qqline(log(USEPUINDXD),lwd=2,lty=3)

qqnorm(chgus, col="tomato", main='')
qqline(chgus,lwd=2,lty=3)


### histograms
par(mfrow=c(2,1))
hist(USEPUINDXD,50,freq=FALSE,col='tomato',border='darkred', xlab= '', main='')
#hist(logus,50,freq=FALSE,col='tomato',border='darkred')
hist(chgus,50,freq=FALSE,col='tomato',border='darkred', main='', xlab='')

### Kernels
par(mfrow=c(2,1))
plot( density(USEPUINDXD) , yaxs='i', xlab='', main='' )
polygon( density(USEPUINDXD), col="tomato", border='darkred')

#plot( density(logus), paste("Kernel density of log EPU"), yaxs='i' )
#polygon( density(logus) , col="tomato" , border='darkred' )

plot( density(chgus) ,yaxs='i', xlab='', main='' )
polygon( density(chgus),col="tomato" , border='darkred' )
dev.off()

```

Moments:
```{r}
### Raw series
cbind("Mean" = mean(USEPUINDXD), "Std. Dev."= sd(USEPUINDXD), "Skewness" = 
skewness(USEPUINDXD), "Kurtosis" = kurtosis(USEPUINDXD))

## Logs
cbind("Mean" = mean(logus), "Std. Dev."= sd(logus), "Skewness" = 
skewness(logus), "Kurtosis" = kurtosis(logus))

## log changes
cbind("Mean" = mean(chgus), "Std. Dev."= sd(chgus), "Skewness" = 
skewness(chgus), "Kurtosis" = kurtosis(chgus))

descrEPU <- as.matrix( c( mean(USEPUINDXD) , sd(USEPUINDXD) , skewness(USEPUINDXD) , kurtosis(USEPUINDXD) ) ) 
dimnames(descrEPU)[[1]] <- list('mean','std. dev.','skew','kurt')

descrLogChgEPU<- as.matrix( c( mean(chgus) , sd(chgus) , skewness(chgus) , kurtosis(chgus) ) ) 
dimnames(descrLogChgEPU)[[1]] <- list('mean','std. dev.','skew','kurt')

```


Carry out tests for stationarity
```{r}
## raw data
adf.test(USEPUINDXD)
## log changes
adf <- adf.test((chgus))
ADF <- as.matrix( c(adf$statistic, adf$p.value ) ) 
dimnames(ADF)[[1]] <- list('Statistic', 'P-Value')
round(ADF, 3)
## logs
#adf.test(log(USEPUINDXD))

```

Jarque-Bera test for normality:
```{r}
## raw data
jarque.test(USEPUINDXD)

## log changes
jb <- jarque.test((chgus))
JB <- as.matrix(c(jb$statistic, jb$p.value))
dimnames(JB)[[1]] <- list('Statistic', 'P-Value')
JB
## logs
jarque.test(log(USEPUINDXD))

```


Autocorrelations:
```{r}
pdf(file='../images/correlations.pdf',width=7,height=5) ### all comments afterwards will split be add to the pdf file (until dev.off)

par(mfrow=c(2,1), mar=c(3,3,3,3))
acf(USEPUINDXD, col='darkorange2', ylim=c(-0.5,1) , lwd=5 , xlim=c(0,25), main='')
#acf(logus, col='darkorange2', ylim=c(-0.5,1) , lwd=5 , xlim=c(0,25) ,  main = "Partial Autocorrelation of log of EPU")
acf(chgus, col='darkorange2', ylim=c(-0.5,1) , lwd=5 , xlim=c(0,25),  main='')

par(mfrow=c(2,1), mar=c(3,3,3,3))
pacf(USEPUINDXD, col='darkorange2', ylim=c(-0.5,1) , lwd=5 , xlim=c(0,25) , main='')
#pacf(logus, col='darkorange2', ylim=c(-0.5,1) , lwd=5 , xlim=c(0,25) ,  main = "Partial Autocorrelation of log of EPU")
pacf(chgus, col='darkorange2', ylim=c(-0.5,1) , lwd=5 , xlim=c(0,25), main='' )



dev.off()

```

Ljung-Box Tests:
```{r}
Box.test(USEPUINDXD , type = c("Ljung-Box"))
#Box.test(logus , type = c("Ljung-Box"))
Box.test(chgus , type = c("Ljung-Box"))

```


