---
title: "Import Predictor data"
author: "Henry Minör"
date: "12 2 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
rm(list=ls())

library(tseries)
library(moments)
library(dplyr)
library(sandwich) ## used to compute NW SE's
library(lmtest)

source('C:/Users/henry/iCloudDrive/Vorlesungen/BA_Economics_UPF/Forecasting Techniques/Codes/Intro to Time Series/lib/utilities.R')
setwd("C:/Users/henry/Dropbox/Forecasting Project")

```

Import data:
```{r}
yields <- read.csv("FRB_H15.csv", skip=5, colClasses="character")

yields <- yields[1:1327, 1:12] %>% filter(yields$RIFLGFCM01_N.B != "ND")
names(yields) <- c("date", "y1mth", "y3mth", "y6mth", "y1yr", "y2yr", "y3yr", "y5yr", "y7yr", "y10yr", "y20yr", "y30yr")
dates <- as.Date( yields$date , '%Y-%m-%d' )
### convert to numeric

yields$y1mth <- as.numeric(y1mth)
yields$y3mth <- as.numeric(y3mth)
yields$y6mth <- as.numeric(y6mth) 
yields$y1yr <- as.numeric(y1yr)
yields$y2yr <- as.numeric(y2yr)
yields$y3yr <- as.numeric(y3yr)
yields$y5yr <- as.numeric(y5yr)
yields$y7yr <- as.numeric(y7yr)
yields$y10yr <- as.numeric(y10yr)
yields$y20yr <- as.numeric(y20yr)
yields$y30yr <- as.numeric(y30yr)


T <- nrow(yields)
```

Compute spreads
```{r}
spread1y_5y <- (yields$y5yr - yields$y1yr)*100
spread1y_10y <- (yields$y10yr - yields$y1yr)*100
spread1y_3y <- (yields$y3yr - yields$y1yr)*100

```


Plot spreads
```{r}

plot(dates, spread1y_10y, type = "l", col=2, main = "Spread vs. 1 year US treasury bonds", ylab="Spread in BP", xlab="date")
lines(dates, spread1y_5y, type = "l", col=3)
lines(dates, spread1y_3y, type = "l", col=4)
abline(h=0, col=1)
grid()
legend('topright',c('10 yr vs. 1yr', '5 yr vs. 1yr','3 yr vs. 1yr' ),col=2:4,lwd=3)

```

Repeat with log differences
```{r}
dspr1y_10y <- diff(spread1y_10y)
dspr1y_3y <- diff(spread1y_3y)
dspr1y_5y <- diff(spread1y_5y)

par(mfrow= c(3,1))
plot(dates[2:T], dspr1y_10y, type = "l", col=2, main = "Differences spreads 10 yr vs. 1 yr US treasury bonds", ylab="Diff in BP", xlab="date")
abline(h=0, col=1)
plot(dates[2:T], dspr1y_5y, type = "l", col=2, main = "Differences spreads 5yr vs. 1 yr US treasury bonds", ylab="Diff in BP", xlab="date")
abline(h=0, col=1)
plot(dates[2:T], dspr1y_3y, type = "l", col=2, main = "Differences spreads 3yr vs. 1 yr US treasury bonds", ylab="Diff in BP", xlab="date")
abline(h=0, col=1)

```

Plots on dristribution:
```{r}

### QQ plots
par(mfrow=c(3,1))
qqnorm(dspr1y_10y,col='tomato',main='10yr vs 1yr')
qqline(dspr1y_10y,lwd=2,lty=3)

qqnorm(dspr1y_5y,col='tomato',main='5yr vs 1yr')
qqline(dspr1y_5y,lwd=2,lty=3)

qqnorm(dspr1y_3y,col='tomato',main='3yr vs 1yr')
qqline(dspr1y_3y,lwd=2,lty=3)

### kernels
par(mfrow=c(3,1))
plot( density(dspr1y_10y) ,paste("Kernel density of 10yr vs 1yr spread diff"), yaxs='i' )
polygon( density(dspr1y_10y), col="tomato", border='darkred' )

plot( density(dspr1y_5y) ,paste("Kernel density of 5yr vs 1yr spread diff"), yaxs='i' )
polygon( density(dspr1y_5y), col="tomato", border='darkred' )

plot( density(dspr1y_3y) ,paste("Kernel density of 3yr vs 1yr spread diff"), yaxs='i' )
polygon( density(dspr1y_3y), col="tomato", border='darkred' )


```

```{r}
### summary
mom10<-cbind("mean"= mean(dspr1y_10y), "std. dev" =  sd(dspr1y_10y), "skewness"=skewness(dspr1y_10y), "kurtosis" = kurtosis(dspr1y_10y))
mom5<-cbind("mean"= mean(dspr1y_5y), "std. dev" =  sd(dspr1y_5y), "skewness"=skewness(dspr1y_5y), "kurtosis" = kurtosis(dspr1y_5y))
mom3<-cbind("mean"= mean(dspr1y_3y), "std. dev" =  sd(dspr1y_3y), "skewness"=skewness(dspr1y_3y), "kurtosis"=kurtosis(dspr1y_3y))
rbind("10yr" = mom10, "5 yr" = mom5, "3yr" = mom3)

```

JB and ADF Test:
```{r}

### ADF-Test
adf.test(dspr1y_10y)
adf.test(dspr1y_5y)
adf.test(dspr1y_3y)

## Jarque Bera Test
jarque.test(dspr1y_10y)
jarque.test(dspr1y_5y)
jarque.test(dspr1y_3y)

## Ljung-Box Test
Box.test(dspr1y_10y, type=c("Ljung-Box"))
Box.test(dspr1y_5y, type=c("Ljung-Box"))
Box.test(dspr1y_3y, type=c("Ljung-Box"))


```

Autocorrelation plot:
```{r}

par(mfrow=c(2,1), mar=c(3,3,3,3))
acf(dspr1y_10y, ylim=c(-0.2,1) , lwd=5 , xlim=c(0,25) , col='darkorange2' , tck=0.02, main="Autocorrelation of dspr1y_10y")
pacf(dspr1y_10y, ylim=c(-0.2,1) , lwd=5 , xlim=c(0,25) , col='darkorange2' , tck=0.02, main="Autocorrelation of dspr1y_10y")

par(mfrow=c(2,1), mar=c(3,3,3,3))
acf(dspr1y_5y, ylim=c(-0.2,1) , lwd=5 , xlim=c(0,25) , col='darkorange2' , tck=0.02, main="Autocorrelation of dspr1y_5y")
pacf(dspr1y_5y, ylim=c(-0.2,1) , lwd=5 , xlim=c(0,25) , col='darkorange2' , tck=0.02, main="Autocorrelation of dspr1y_5y")

par(mfrow=c(2,1), mar=c(3,3,3,3))
acf(dspr1y_3y, ylim=c(-0.2,1) , lwd=5 , xlim=c(0,25) , col='darkorange2' , tck=0.02, main="Autocorrelation of dspr1y_3y")
pacf(dspr1y_3y, ylim=c(-0.2,1) , lwd=5 , xlim=c(0,25) , col='darkorange2' , tck=0.02, main="Autocorrelation of dspr1y_3y")



```


